# version: "3.7" # Uncomment for older compose versions
volumes:
  db_data:

services:
  # app:
  #   container_name: "${APP_NAME}"
  #   build: 
  #     context: .
  #     target: development
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   environment:
  #     DB_ENGINE: "${DB_ENGINE}"
  #     DB_NAME: "${DB_NAME}"
  #     DB_USERNAME: "${DB_USERNAME}"
  #     DB_PASSWORD: "${DB_PASSWORD}"
  #     DB_HOST: "${APP_HOST}"
  #   volumes:
  #     - ./app:/app
  #     - db
  db:
    image: mysql:8.0
    container_name: youtube_bd
    tty: true
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "youtube_bd"
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - db_data:/var/lib/mysql
